# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, null=True)),
                ('likes', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_reviews')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('length', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='video_user')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vod.Video', verbose_name='video_reviews'),
        ),
        migrations.AddField(
            model_name='likereview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vod.Review', verbose_name='review_likes'),
        ),
        migrations.AddField(
            model_name='likereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_likes'),
        ),
    ]
