# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0002_auto_20160614_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
