# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0004_auto_20160616_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsereview',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
