# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0005_auto_20160616_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
